services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    region: frankfurt
    image:
      url: docker.n8n.io/n8nio/n8n

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # n8n Postgres configuration (wired to the Render Postgres below)
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      # Optional but safe to include; n8n defaults to 5432 if omitted
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port

databases:
  - name: n8n-db
    plan: free
    region: frankfurt
    diskSizeGB: 1
    # Use the newest supported major unless you have a reason for 16
    postgresMajorVersion: "17"
